name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run ZAP Scan
      run: |
        npm install
        node generate-issues.js
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        GITHUB_RUN_NAME: ${{ github.event_name }}-${{ github.run_number }}  
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
